### ISSUE TITLE
Problem with initialising map

### ISSUE THREAD

**Issue by xiendong** [terzakig/gptam#10]
Hello, thanks once again for your prompt reply. gcalibrator worked just as expected, but I have a problem with gptam.

When I attempt to generate an initial map (by pressing spacebar once, translate my camera, and press the spacebar again), I encountered this error on the file `SO3.h`

```
Assertion failed: ((mat_.row(0) ^ mat_.row(1)).dot(mat_.row(2)) > 0 && "Coercing did not produce a rotation matrix, or you gave me low-rank materials!"), function coerce, file /Users/xiendongwang/Documents/WANGXD/2019/FYP/opencv-ptam/gptam-master/GCVD/SO3.h, line 190.
Abort trap: 6
```

And crashed with Abort trap 6. May I know what should I do to fix it? Thank you so much!

The full console log is as below:
```
  Visual Tracking and Mapping with OpenCV
  --------------- 


 University of Portsmouth 2016  Based on PTAM by Klein and Murray (Isis Innovation Limited 2008)
   

  Parsing settings.cfg ....
! GUI_impl::Loadfile: Failed to load script file "settings.cfg".
  Initiating capture device (whatever it is)...
>   Now capturing....
 Screen size (width , height) : 1280 , 720
? PV3::Register: cv::Vec<float, 5> Camera.Parameters undefined. Defaults to [ 0 0 0 0 0 ]
Got passed the preliminary camera test... Now need to create: 
a. The Map!
DEBUG: Ditched 0 trashed map points! I hope...
DONE
b. The Mapmaker Threadf!
DEBUG: Ditched 0 trashed map points! I hope...
attempting to start the mapmaker ...
DONE
c. The Tracker!
Waiting for mapmaker to reset ...
DEBUG: Ditched 0 trashed map points! I hope...
DONE
d. The The AR Driver!
DONE
e. The Map Viewer!
DONE
  ARDriver: Creating FBO...  .. created FBO.
Assertion failed: ((mat_.row(0) ^ mat_.row(1)).dot(mat_.row(2)) > 0 && "Coercing did not produce a rotation matrix, or you gave me low-rank materials!"), function coerce, file /Users/xiendongwang/Documents/WANGXD/2019/FYP/opencv-ptam/gptam-master/GCVD/SO3.h, line 190.
Abort trap: 6
```

**Comment by terzakig** [comment]
Hello again,


The assertion means that somehow very small numbers(I am guessing close to zero)  in the camera pose were produced and the rotation matrix unit vectors cannot be normalized.

Also, I see PTAM did not find the "settings.cfg". I am guessing you haven't calibrated the camera, which would account for the degenerate results.

So, if I am not wrong, you need to run the calibrator and copy the results in a files "settings.csfg" in the same directory with the PTAM executable (see the README towards the end).

Hope that solves your problem
________________________________

**Comment by xiendong** [comment]
Oops, I ran the executable outside the build folder. That explains why `settings.cfg` was not found.

So, I paid attention to the number of trails and try again. The assertion is gone now but still throws `Abort trap: 6` error though. Any idea why?

Here's a part of the console log from a sample run:

```
a. The Map!
DEBUG: Ditched 0 trashed map points! I hope...
DONE
b. The Mapmaker Threadf!
DEBUG: Ditched 0 trashed map points! I hope...
attempting to start the mapmaker ...
DONE
c. The Tracker!
Waiting for mapmaker to reset ...
DEBUG: Ditched 0 trashed map points! I hope...
DONE
d. The The AR Driver!
DONE
e. The Map Viewer!
DONE
  ARDriver: Creating FBO...  .. created FBO.
Abort trap: 6
```

**Comment by terzakig** [comment]
The number of correspondences is unusually small during initialization. Again, if this is issue is persistent, this suggests a bad or non-existent  calibration, or perhaps bad quality of tracking in the initialization. If all your efforts to initialize produce similar results, then it must be the calibration. I assume you ran the calibration (?)
________________________________

**Comment by xiendong** [comment]
Hello, apologies for the delayed response due to my school work. I bought a separate webcam and tried again. Calibration worked fine, and I discovered that I could start the whole tracking process if the initial number of corners was less than 20. However, if there were too many corners, it would still crash with `Abort trap: 6`.

So, I went on to build the project with `Address Sanitizer` together with `lldb` and tried running the initialising sequence again. I discovered that the crash occurred in `EssentialInit.cpp`. It seems that there is out-of-bounds array access with `anIndices` in the method `BestEssentialFromMatches_MLESAC`. `anIndices` has size 4, but a for loop may access up to index 7 of the array. 

May I ask which should be the correct size of the array? Thanks!

**Comment by terzakig** [comment]
Thanks Xien, indeed this was a big. I tried to make essential init of similar structure to homography init, so I copied the RANSAC (MLESAC) function over and forgot to change the number of cached indices from 4 (homography) to 8 (essential matrix). Fix pushed.
________________________________

**Comment by xiendong** [comment]
Thanks for resolving the first issue. I tried to run `gptam` with the fix, but encountered another crash. This time is another memory out-of-bounds access error with the `mutemp` variable in `EssentialInit::RefineEssentialWithInliers`. 

It seems to me that `mutemp` is an array of size 5, but crashes in the method `Rotation2Quaternion(const Pr *R)` (that was called by a constructor of Quaternion from this line `Quaternion<> qtmp(mutemp.val)`) as there are array accesses to indices 5 or larger (i.e. R[5], ... , R[8]). 

Any idea what went wrong? Thank you!

**Comment by terzakig** [comment]
Hi Xien Dong, I uploaded a fix for your issue. It seems that these bugs were introduced when I update the quaternion header file in order to be consisistent with the one in my Quaternion repository. I think this was the last problem!
________________________________

**Comment by xiendong** [comment]
Hello @terzakig, apologies for the late reply, was busy with schoolwork for the past few days. And thanks for your fixes, it seems to work fine so far. Will let you know if I encounter any further issues! 
Thank you so much!
