### ISSUE TITLE
Compile Error on Mac OS 10.14.4

### ISSUE THREAD

**Issue by KaoruMuta** [terzakig/gptam#11]
I have a problem on running your code.

```
ld: library not found for -lglut
clang: error: linker command failed with exit code 1 (use -v to see invocation) 
make[2]: *** [gptam] Error 1 
make[1]: *** [CMakeFiles/gptam.dir/all] Error 2 
make: *** [all] Error 2
```

I meet these errors and cannot still solve it... 

If you have time, please give me an opinion to solve these errors...

**Comment by terzakig** [comment]
Hello,

Thanks for your inrterest in this piece of work. It looks like OpenGL is not installed or cannot be used for some reason. I am guessing that (re)installing it will solve the problem.

Hope this helps

George
________________________________

**Comment by KaoruMuta** [comment]
Thanks for your advice. I was able to solve this problem.
If I have any problem about this program, I will probably ask you again.

Best regards.

Kaoru Muta

**Comment by chrissisura** [comment]
@KaoruMuta how did you manage to fix it?

**Comment by KaoruMuta** [comment]
@chrissisura 
Sorry for late reply.
As far as I remember, I tried to reinstall OpenGL and then the program ran correctly.
