### ISSUE TITLE
get rotation and translation matrix for each keframe.

### ISSUE THREAD

**Issue by dorc23** [terzakig/gptam#15]
hey ,
there is any way to get from the gptam rotation and translation matrix for each keyframe?

**Comment by terzakig** [comment]
Yes, there is. The transformation is stored in an SE3 member of Keyframe named se3CfromW. You can extract the rotation as a cv::Matx<float, 3, 3> matrix and the translation as a cv::Vec<float, 3> using methods SE3<>::get_rotation()::get_matrix() and SE3<>::get_translation() (see files GCVD/SE3.h and GCVD/SO3.h  for more).
________________________________

**Comment by dorc23** [comment]
thanks for your help , i print the member se3CfromW :

[0.88020974, -1.8626451e-09, -0.47458485;
 -0.035426091, -0.99721009, -0.065704562;
 -0.47326079, 0.07464648, -0.87775403]

[0.291526, -0.207595, 0.995936]

the first object is the rotation matrix ? and the second is the translation vec?
