### ISSUE TITLE
can i get the intrinsic camera matrix of each keyframe ?

### ISSUE THREAD

**Issue by dorc23** [terzakig/gptam#16]
can i get from the code for each keyframe what was the camera intrinsic matrix?
cameraMatrix – Output 3x3 floating-point camera matrix K

**Comment by terzakig** [comment]
Hi,

Each keyframe is assumed to be generated by the same camera and therefore there is no camera member in the KeyFrame class. Consequently, a more appropriate location for this "global" camera model is the Tracker class (see member  mCamera of type ATANCamera inside the Tracker class). The intrinsics are then computed inside the various methods of mCamera. the parameters are originally retrieved in a persistent vector (i.e. loaded from file) mpvvCameraParams which is a memebr of ATANCamera. Now, to get fx, fy, cx, cy and the distortion coefficient coefficient (stored in the same order inside mpvvCameraParams) you simply multiply by the width/height these figures. For instance:

fx = mpvvCameraParams[0] * image_width
fy = mpvvCameraParams[1] * image_height
cx = mpvvCameraParams[2] * image_width
cy = mpvvCameraParams[3] * image_height

The last parmeter in mpvvCameraParams is the distortion coefficient which is computed using a fisheye distortion model, known as the ATAN2 distortion model (see more in the comments).
________________________________

**Comment by dorc23** [comment]
thanks for your informative answer , i can get the intrinsic matrix of each keyframe if i get his projection matrix , the projection matrix of each keyframe save in any attribute in this process?

**Comment by terzakig** [comment]
The projection matrix is implicitly inferred by the intrinsics (K) , R and t for every keyframe, so you will not find it. You can easily compute it as follows;

P = K*[R | t] 

But note that to use this matrix directly on a point in the world you must remove radial distortion at the Euclidean plane of projection before projecting onto the the images. To ue the projection matrix, you need to ensure that the images you are working on are devoid of radial distortion. Removing radial distortion on the entire image in sparse visual SLAM is an expensive operation and is not necessary. Thus, projection is modeled as follows:

1) Project world point Pw to Camera frame point Pc:
Pc = R*Pw + t

2) Get the acual Euclidean projection m_u (u stands for 'u'ndistorted):
m_u = Pc / Pc(3)

3) Undistort the Euclidean projection m_u into m_d (d stands for 'd'istorted) using the ATAN2 model:
mu = Distort(md)   // note: Distort() is a non-linear operation that cannot be represented with up-to-scale matrix multiplications

4) Finally, project to Image:
m_i = K * m_d

**Comment by dorc23** [comment]
where is the best place to put thins calculations : 
fx = mpvvCameraParams[0] * image_widththose
fy = mpvvCameraParams[1] * image_height
cx = mpvvCameraParams[2] * image_width
cy = mpvvCameraParams[3] * image_height
to make sure that i get the camera intrinsic matrix of each keyframe that taken ?

**Comment by dorc23** [comment]
where is the best place to put those calculations :
fx = mpvvCameraParams[0] * image_widththose
fy = mpvvCameraParams[1] * image_height
cx = mpvvCameraParams[2] * image_width
cy = mpvvCameraParams[3] * image_height
to make sure that i get the camera intrinsic matrix of each keyframe that taken ?
