### ISSUE TITLE
fatal error: readline/readline.h

### ISSUE THREAD

**Issue by mrgransky** [terzakig/gptam#6]
Hi,

I am trying to compile the code using following procedure:

```
$ git clone https://github.com/terzakig/gptam.git 
$ cd gptam/
$ mkdir build && cd build
$ cmake .. (works fine)
$ make 
```

I get the following error:

```
In file included from /home/farid/WS_Farid/gptam/Persistence/GUI.cpp:5:0:
/home/farid/WS_Farid/gptam/Persistence/GUI_impl.h:25:31: fatal error: readline/readline.h: No such file or directory
compilation terminated.
CMakeFiles/gcalibrator.dir/build.make:662: recipe for target 'CMakeFiles/gcalibrator.dir/Persistence/GUI.cpp.o' failed
make[2]: *** [CMakeFiles/gcalibrator.dir/Persistence/GUI.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/gcalibrator.dir/all' failed
make[1]: *** [CMakeFiles/gcalibrator.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
My system: Ubuntu 16.04 LTS with OpenCV3, gcc 5.4.0
Cheers;

**Comment by terzakig** [comment]
Hi, this is a linux library used by persistence (actually used by the original GVars library). I think you should be able to solve this by installing it:

sudo apt-get install libreadline-dev

Hope this will resolve the problem.

________________________________

**Comment by mrgransky** [comment]
tnx man!
All good!

**Comment by PRABHUGUPTA** [comment]
Hi,

I am trying to compile the code

while doing make, I am getting the following error:

CMakeFiles/gptam.dir/PatchFinder.cpp.o: In function `std::ostream& cv::operator<< <float, 3, 3>(std::ostream&, cv::Matx<float, 3, 3> const&)':
PatchFinder.cpp:(.text+0x30da): undefined reference to `cv::Formatter::get(int)'
CMakeFiles/gptam.dir/PatchFinder.cpp.o: In function `cv::String::String(char const*)':
PatchFinder.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x4d): undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/gptam.dir/PatchFinder.cpp.o: In function `cv::String::~String()':
PatchFinder.cpp:(.text._ZN2cv6StringD2Ev[_ZN2cv6StringD5Ev]+0x14): undefined reference to `cv::String::deallocate()'
CMakeFiles/gptam.dir/PatchFinder.cpp.o: In function `cv::Mat::Mat(int, int, int, void*, unsigned long)':
PatchFinder.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x136): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
PatchFinder.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x225): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
CMakeFiles/gptam.dir/PatchFinder.cpp.o: In function `void cv::SVD::compute<float, 3, 3, 3>(cv::Matx<float, 3, 3> const&, cv::Matx<float, 3, 1>&, cv::Matx<float, 3, 3>&, cv::Matx<float, 3, 3>&)':
PatchFinder.cpp:(.text._ZN2cv3SVD7computeIfLi3ELi3ELi3EEEvRKNS_4MatxIT_XT0_EXT1_EEERNS2_IS3_XT2_ELi1EEERNS2_IS3_XT0_EXT2_EEERNS2_IS3_XT1_EXT2_EEE[_ZN2cv3SVD7computeIfLi3ELi3ELi3EEEvRKNS_4MatxIT_XT0_EXT1_EEERNS2_IS3_XT2_ELi1EEERNS2_IS3_XT0_EXT2_EEERNS2_IS3_XT1_EXT2_EEE]+0x1e3): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
CMakeFiles/gptam.dir/MapMaker.cpp.o: In function `std::ostream& cv::operator<< <float, 3, 3>(std::ostream&, cv::Matx<float, 3, 3> const&)':
MapMaker.cpp:(.text+0x8c30): undefined reference to `cv::Formatter::get(int)'
CMakeFiles/gptam.dir/Tracker.cpp.o: In function `std::ostream& cv::operator<< <float, 3, 3>(std::ostream&, cv::Matx<float, 3, 3> const&)':
Tracker.cpp:(.text+0x72e5): undefined reference to `cv::Formatter::get(int)'
CMakeFiles/gptam.dir/HomographyInit.cpp.o: In function `void cv::SVD::compute<double, 9, 9, 9>(cv::Matx<double, 9, 9> const&, cv::Matx<double, 9, 1>&, cv::Matx<double, 9, 9>&, cv::Matx<double, 9, 9>&)':
HomographyInit.cpp:(.text._ZN2cv3SVD7computeIdLi9ELi9ELi9EEEvRKNS_4MatxIT_XT0_EXT1_EEERNS2_IS3_XT2_ELi1EEERNS2_IS3_XT0_EXT2_EEERNS2_IS3_XT1_EXT2_EEE[_ZN2cv3SVD7computeIdLi9ELi9ELi9EEEvRKNS_4MatxIT_XT0_EXT1_EEERNS2_IS3_XT2_ELi1EEERNS2_IS3_XT0_EXT2_EEERNS2_IS3_XT1_EXT2_EEE]+0x1e3): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
CMakeFiles/gptam.dir/Bundle.cpp.o: In function `std::ostream& cv::operator<< <float, 3, 3>(std::ostream&, cv::Matx<float, 3, 3> const&)':
Bundle.cpp:(.text+0x1fca): undefined reference to `cv::Formatter::get(int)'
CMakeFiles/gptam.dir/VideoSource.cpp.o: In function `VideoSource::VideoSource()':
VideoSource.cpp:(.text+0x6c): undefined reference to `cv::VideoCapture::VideoCapture(int)'
collect2: error: ld returned 1 exit status
CMakeFiles/gptam.dir/build.make:793: recipe for target 'gptam' failed
make[2]: *** [gptam] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/gptam.dir/all' failed
make[1]: *** [CMakeFiles/gptam.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

My system: Ubuntu 18.04 LTS with OpenCV2
