### ISSUE TITLE
build on ubuntu 14.04

### ISSUE THREAD

**Issue by chajk** [terzakig/gptam#7]
Hi

I am looking into your release to run on top of ubuntu 14.04.5 lts. 
To build binary, I followed cmake CMakeLists.txt .. from build directory in gptam project folder.
Below is my printed message. 

CMakeLists.txt
----------------------------------
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_C_COMPILER "g++")
----------------------------------

root@ubuntu:~/Work/gptam-master/build# cmake CMakeLists.txt ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Configuring done
-- Generating done
-- Build files have been written to: /root/Work/gptam-master/build

Then compiler option error is occurred when I ran make as below

root@ubuntu:~/Work/gptam-master/build# make
Scanning dependencies of target gcalibrator
[  1%] Building CXX object CMakeFiles/gcalibrator.dir/CameraCalibrator.cpp.o
c++: error: unrecognized command line option ‘-std=c++14’
make[2]: *** [CMakeFiles/gcalibrator.dir/CameraCalibrator.cpp.o] Error 1
make[1]: *** [CMakeFiles/gcalibrator.dir/all] Error 2
make: *** [all] Error 2
root@ubuntu:~/Work/gptam-master/build# 

I tried to change default CXX_STANDARD to 11 and indicating C Compiler to G++. However the problem is still reproducible. Should I upgrade g++ to 5.2 later?

Please let me know the detailed build step. or your environment to build this code.
thanks.

**Comment by terzakig** [comment]
Hi Jack,

I recently added a new initialization method using epipolar geometry and it makes use of C++14 features. You may want to checkout your repository at a previous stage (to get the appropriate head, see this thread in which a similar issue was reported: https://github.com/terzakig/gptam/issues/4 ). 

Try this out and let me know if it works out for you.
