### ISSUE TITLE
linking cv issue

### ISSUE THREAD

**Issue by PRABHUGUPTA** [terzakig/gptam#8]
Hi,

I am trying to compile the code using following procedure:

```
$ git clone https://github.com/terzakig/gptam.git 
$ cd gptam/
$ mkdir build && cd build
$ cmake .. (works fine)
$ make 
```
I get the following error:

```
CMakeFiles/gptam.dir/PatchFinder.cpp.o: In function `std::ostream& cv::operator<< <float, 3, 3>(std::ostream&, cv::Matx<float, 3, 3> const&)':
PatchFinder.cpp:(.text+0x30da): undefined reference to `cv::Formatter::get(int)'
CMakeFiles/gptam.dir/PatchFinder.cpp.o: In function `cv::String::String(char const*)':
PatchFinder.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x4d): undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/gptam.dir/PatchFinder.cpp.o: In function `cv::String::~String()':
PatchFinder.cpp:(.text._ZN2cv6StringD2Ev[_ZN2cv6StringD5Ev]+0x14): undefined reference to `cv::String::deallocate()'
CMakeFiles/gptam.dir/PatchFinder.cpp.o: In function `cv::Mat::Mat(int, int, int, void*, unsigned long)':
PatchFinder.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x136): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
PatchFinder.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x225): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
CMakeFiles/gptam.dir/PatchFinder.cpp.o: In function `void cv::SVD::compute<float, 3, 3, 3>(cv::Matx<float, 3, 3> const&, cv::Matx<float, 3, 1>&, cv::Matx<float, 3, 3>&, cv::Matx<float, 3, 3>&)':
PatchFinder.cpp:(.text._ZN2cv3SVD7computeIfLi3ELi3ELi3EEEvRKNS_4MatxIT_XT0_EXT1_EEERNS2_IS3_XT2_ELi1EEERNS2_IS3_XT0_EXT2_EEERNS2_IS3_XT1_EXT2_EEE[_ZN2cv3SVD7computeIfLi3ELi3ELi3EEEvRKNS_4MatxIT_XT0_EXT1_EEERNS2_IS3_XT2_ELi1EEERNS2_IS3_XT0_EXT2_EEERNS2_IS3_XT1_EXT2_EEE]+0x1e3): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
CMakeFiles/gptam.dir/MapMaker.cpp.o: In function `std::ostream& cv::operator<< <float, 3, 3>(std::ostream&, cv::Matx<float, 3, 3> const&)':
MapMaker.cpp:(.text+0x8c30): undefined reference to `cv::Formatter::get(int)'
CMakeFiles/gptam.dir/Tracker.cpp.o: In function `std::ostream& cv::operator<< <float, 3, 3>(std::ostream&, cv::Matx<float, 3, 3> const&)':
Tracker.cpp:(.text+0x72e5): undefined reference to `cv::Formatter::get(int)'
CMakeFiles/gptam.dir/HomographyInit.cpp.o: In function `void cv::SVD::compute<double, 9, 9, 9>(cv::Matx<double, 9, 9> const&, cv::Matx<double, 9, 1>&, cv::Matx<double, 9, 9>&, cv::Matx<double, 9, 9>&)':
HomographyInit.cpp:(.text._ZN2cv3SVD7computeIdLi9ELi9ELi9EEEvRKNS_4MatxIT_XT0_EXT1_EEERNS2_IS3_XT2_ELi1EEERNS2_IS3_XT0_EXT2_EEERNS2_IS3_XT1_EXT2_EEE[_ZN2cv3SVD7computeIdLi9ELi9ELi9EEEvRKNS_4MatxIT_XT0_EXT1_EEERNS2_IS3_XT2_ELi1EEERNS2_IS3_XT0_EXT2_EEERNS2_IS3_XT1_EXT2_EEE]+0x1e3): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
CMakeFiles/gptam.dir/Bundle.cpp.o: In function `std::ostream& cv::operator<< <float, 3, 3>(std::ostream&, cv::Matx<float, 3, 3> const&)':
Bundle.cpp:(.text+0x1fca): undefined reference to `cv::Formatter::get(int)'
CMakeFiles/gptam.dir/VideoSource.cpp.o: In function `VideoSource::VideoSource()':
VideoSource.cpp:(.text+0x6c): undefined reference to `cv::VideoCapture::VideoCapture(int)'
collect2: error: ld returned 1 exit status
CMakeFiles/gptam.dir/build.make:793: recipe for target 'gptam' failed
make[2]: *** [gptam] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/gptam.dir/all' failed
make[1]: *** [CMakeFiles/gptam.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```
My system: Ubuntu 18.04 LTS with OpenCV3 gcc 7.3.0

I think it's an opencv linking error, but not able to debug...................

**Comment by terzakig** [comment]
Hi,

Thanks for looking into this piece of work.

Yes, this is a linker error. I suspect that you need to include the appropriate .so file in the CmakeLists.txt. I am manually including the library files, so look for the following:

Set( OpenCV_LIBS
"/usr/local/lib/libopencv_calib3d.so"
...
...
...

Uncomment all .so files that are commented out and if this doesn't do the job, go to your /usr/local/lib manually include all the missing .so files to be on the safe side. That's a quick way of fixing this. Alternatively (and ideally) you can modify the CMakeLists.txt to find OpenCV automatically with find_package() and  FindOpenCV.cmake file.

Hope the above is helpful
________________________________

**Comment by PRABHUGUPTA** [comment]
Thanks for your suggestions......
I have tried to include all .so files as well but same error is coming.............
opencv is working in my system but not able to link it............
As to compile a sample we write "g++ -o test_1 test_1.cpp `pkg-config opencv --cflags --libs`" in order to link with opencv....................
How to do the same with make.................using Cmake
Looking forward to your valuable suggestion.....................

**Comment by terzakig** [comment]
This is obviously some OpenCV version /build minor incompatibilty, so the linker is trying to find some .so file that in some other configuration is accessible. Your command line g++ invokation with OpenCV libs is a good starting point, but your cannot use it, unless you are prepared to add a buch of source files and a few include directorys in a single command line .

Here's one suggestion for a quick fix: I am not entirely sure if this is valid, but you could try to add the string "pkg-config opencv --cflags --libs" to the linker flags in the CMakeLists.txt and this could solve your problem.

Another suggestion for an easy way out, which would work, is to navigate inside the urs/local/libs directory on your computer and find all the .so files associated with opencv (they should be named "libopencvXXXXX" and then add the names that are missing from the respective list in the CMakeLists.txt. This is an ugly way of solving this problem, but I think if you include all the OpenCV .so files you should at least be able to compile.
________________________________

**Comment by PRABHUGUPTA** [comment]
I am very thankful for your valuable suggestion and quick response...............
Although it worked for me after downgrading to 16.04 lts ubuntu version along with opencv 3.0 version and linking with the folder of opencv.......................

tnx man!

**Comment by terzakig** [comment]
No problem, happy that the problem is resolved.
________________________________

**Comment by PRABHUGUPTA** [comment]
Hi.........
I was trying to understand the functionality of the program and to include multiple ar objects not only on the initial keyfram but onto other keyframe as well..........but was not able to figure out exactly at which line in the code is the command to set up a particular key frame onto which printing (eye drawing) is done is give............... 
Looking forward to your valuable suggestion.....................

**Comment by terzakig** [comment]
Hello,

I think what you are looking for is in System.cpp, particularly the following line:

mpARDriver->Render(mimFrameRGB, mpTracker->GetCurrentPose());
________________________________

**Comment by PRABHUGUPTA** [comment]
In my opinion flow is going as follows:
from main....->.....system....->.....tracker...........(via................ mpTracker->TrackFrame(mimFrameBW,!bDrawAR && !bDrawMap,mimFrameRGB);...............).............->...............trackframe....->.....trackforinitmap....->.....(mMapMaker.InitFromStereo<EssentialInit>(pFirstKF, pCurrentKF, vMatches, mse3CamFromWorld);-------------->---------InitFromStereo (which is in mapmaker.h)....................but where in mapmaker.h or in essential.h is the  grid position is being set over which 3d objetcs are drawn using eyegame.h........

but was not able to figure out exactly at which line in the code is the command to set up a particular key frame onto which printing (eye drawing) is done...........

If there is any fault in the flow i observed from the code........plss let me know............

very thankful for your quick response...............:)
