### ISSUE TITLE
Compatibility for macOS

### ISSUE THREAD

**Issue by xiendong** [terzakig/gptam#9]
Hello, I would like to ask if this library is compatible with macOS? I tried to compile the original PTAM with libcvd on the latest macOS without success since the code is really outdated. Then, I stumble upon your adaptation to OpenCV.

I tried to make numerous customisations to the code base to make it compilable with macOS, but I am stuck with this error at around 60% completion:
`ld: library not found for -lglut`

When I changed from `SET( GL_LINKER_FLAGS "-lglut -lGLU -lGL")` to `SET( GL_LINKER_FLAGS "-framework OpenGL -framework GLUT")` (though I don't think it works), it shows up another error:
`ld: symbol(s) not found for architecture x86_64`, seems to be due to X11 by XQuartz.

I tried adding `-lX11` to the linker flags, but of course, I don't think it solves the problem.

![image](https://user-images.githubusercontent.com/11458867/53679745-aee9c000-3d0b-11e9-8d4f-1878f054dfec.png)
[...additional errors removed...]
![image](https://user-images.githubusercontent.com/11458867/53679750-c0cb6300-3d0b-11e9-9609-065809f18320.png)

Any clue on this? Thank you!

**Comment by terzakig** [comment]
Hello,

Very happy to see you in this piece of work. As stated in the readme, I more-less kept the original graphical user interface designed by George Klein, which makes use of X11 for dialogs. I conjecture that your problem (and the solution) is described here: https://support.apple.com/en-gb/HT201341
About X11 for Mac<https://support.apple.com/en-gb/HT201341>
X11 is no longer included with Mac, but X11 server and client libraries are available from the XQuartz project.
support.apple.com

Hope it's helpful.
________________________________

**Comment by xiendong** [comment]
Hello, thanks for the swift reply. I have managed to solve the compilation issue by adding the linker flag in two places of `target_link_libraries` in `CMakeLists.txt`. The code base compiles and runs on macOS! However, I do have a problem running gptam. I shall create a separate issue. Thanks!
